#!/bin/bash

echo "=== Agent Diagnostic ==="
echo ""
echo "1. Agent Process:"
ps aux | grep "node.*agent" | grep -v grep || echo "   ❌ Not running"
echo ""
echo "2. Compiled Files:"
ls -la agents/dist/handoff-tools.js 2>/dev/null && echo "   ✅ handoff-tools.js exists" || echo "   ❌ handoff-tools.js missing"
ls -la agents/dist/agent-runtime-s2s.js 2>/dev/null && echo "   ✅ agent-runtime-s2s.js exists" || echo "   ❌ agent-runtime-s2s.js missing"
echo ""
echo "3. Workflow File:"
ls -la backend/workflows/workflow_triage.json 2>/dev/null && echo "   ✅ workflow_triage.json exists" || echo "   ❌ workflow_triage.json missing"
echo ""
echo "4. AWS Credentials:"
[ -n "$AWS_ACCESS_KEY_ID" ] && echo "   ✅ AWS_ACCESS_KEY_ID set" || echo "   ❌ AWS_ACCESS_KEY_ID not set"
[ -n "$AWS_SECRET_ACCESS_KEY" ] && echo "   ✅ AWS_SECRET_ACCESS_KEY set" || echo "   ❌ AWS_SECRET_ACCESS_KEY not set"
echo ""
echo "5. Gateway:"
curl -s http://localhost:8080/health > /dev/null && echo "   ✅ Gateway responding" || echo "   ❌ Gateway not responding"
echo ""
echo "6. Registered Agents:"
curl -s http://localhost:8080/api/agents 2>/dev/null | jq -r '.[].id' 2>/dev/null || echo "   ❌ Cannot fetch agents"
echo ""
echo "7. Personas:"
curl -s http://localhost:8080/api/personas 2>/dev/null | jq -r '.[].id' 2>/dev/null || echo "   ❌ Cannot fetch personas"
echo ""
echo "=== Diagnostic Complete ==="
