#!/bin/bash
# rollback_connect_assets.sh
# 
# This script removes the temporary assets generated by the Amazon Connect integration testing.
# It cleans up the dynamically generated S3 audio files and the registered Connect Prompts.

set -e

CONNECT_INSTANCE_ID="8dc186bb-1a4b-42ab-b91b-d8acd52f00fc"
CONNECT_AUDIO_BUCKET="amazon-connect-d353370efd55"
REGION="us-west-2"
DYNAMODB_TABLE="voice_s2s_sessions"

echo "=========================================="
echo "Rolling back Amazon Connect test assets..."
echo "=========================================="

# 1. Delete generated WAV files in S3
echo "[1/3] Deleting generated audio files from S3 buffer bucket ($CONNECT_AUDIO_BUCKET)..."
aws s3 rm "s3://$CONNECT_AUDIO_BUCKET/connect/archdemos/voice-s2s-turns/" --recursive
echo "✓ S3 audio files deleted."

# 2. Delete Dynamically Created Connect Prompts
echo "[2/3] Deleting dynamically created Connect prompts (vs2s-*)..."
aws connect list-prompts --instance-id "$CONNECT_INSTANCE_ID" --region "$REGION" \
    --query "PromptSummaryList[?starts_with(Name, 'vs2s-')].[Id,Name]" --output text | \
while read -r promptId promptName; do
    if [ -n "$promptId" ] && [ "$promptId" != "None" ]; then
        echo "  Deleting prompt: $promptName ($promptId)"
        aws connect delete-prompt --instance-id "$CONNECT_INSTANCE_ID" --prompt-id "$promptId" --region "$REGION" || true
    fi
done
echo "✓ Connect prompts deleted."

# 3. Clean up DynamoDB Session state history
echo "[3/3] Cleaning up DynamoDB Session entries..."
aws dynamodb scan --table-name "$DYNAMODB_TABLE" --region "$REGION" \
    --query "Items[*].sessionId.S" --output text | tr '\t' '\n' | \
while read -r sessionId; do
    if [ -n "$sessionId" ]; then
        echo "  Deleting session: $sessionId"
        aws dynamodb delete-item --table-name "$DYNAMODB_TABLE" \
            --key "{\"sessionId\": {\"S\": \"$sessionId\"}}" --region "$REGION" || true
    fi
done
echo "✓ DynamoDB session state cleared."

echo "=========================================="
echo "Rollback of temporary runtime assets complete."
echo "Note: If you wish to completely remove the integration infrastructure (Lambdas, IAM Roles),"
echo "please revert the changes made to aws/cloudformation.yaml and redeploy the CloudFormation stack."
echo "=========================================="
